---
- name: Read device information
  community.general.parted: device=/dev/sda unit=MiB
  register: sda_info

- name: Create a 40GiB partition for Docker
  parted:
    device: /dev/sda
    number: 2
    state: present
    part_start: "{{ sda_info.partitions[0].end }}MiB"
    part_end: "{{ sda_info.partitions[0].end + 40960 }}MiB"

- name: Format partition as ext4
  filesystem:
    dev: /dev/sda2
    fstype: ext4

- name: Mount Docker partition
  ansible.posix.mount:
    src: /dev/sda2
    path: /var/lib/docker
    state: mounted
    fstype: ext4
